### ISSUE TITLE
'nil' is not compatible with expected argument type 'LSSharedFileListItem

### ISSUE THREAD

**Issue by ghost** [chrenn/LoginItemKit#3]
Hey!

Since XCode 13.1 and macOS Monterey I can't built my project due to `'nil' is not compatible with expected argument type 'LSSharedFileListItem'` error in `line 29`.

It looks like `insertAfterThisItem` property in `LSSharedFileListInsertItemURL` is no longer optional.

**Comment by lwouis** [comment]
There are 2 issues:

* SDK 12 made `insertAfterThisItem` non-optional
* Apple introduced a runtime bug on the M1 architecture where specifying `kLSSharedFileListItemBeforeFirst` crashes whereas it runs fine on Intel architecture. https://github.com/chrenn/LoginItemKit/pull/1 attempted to address that, but is stuck regarding the previous point because of it

Regarding the first issue (which OP mentions), you could compile using SDK 11 (compiling from Xcode < 13). It's an option, unless you need SDK 12 for some new API.

If you're compiling for M1, or if you need SDK 12, then you're out of luck. I don't see how to handle this. I'm sharing here my [investigations and attempts to work around the issue](https://github.com/lwouis/alt-tab-macos/pull/1094#issuecomment-969025187).

Maybe @chrenn can see a solution I don't see 🙏

**Comment by chrenn** [comment]
Thanks for the input! I'll have a look in the coming days as I currently don't have enough disk space to install the latest Xcode version and/or Monterey beta. 😬

**Comment by lwouis** [comment]
Monterey is no longer in Beta. It's been released officially a few weeks ago i believe 👍
